### ISSUE TITLE
Can you make the code public?

### ISSUE THREAD

**Issue by smsubham** [tingyaohsu/SciCap#1]
Hi,
Found this paper to be really interesting. Can you please open source the code for this paper?

**Comment by tingyaohsu** [comment]
Hi,
Thank you for being interested in our work! Our code is not currently in the form that is easy to share. The baseline captioning models we used (CNN+LSTM) were based on papers published a while ago (~2016). So it should be relatively easy to find other people's implementations of these models on GitHub.
